apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/version: 34e644a9c9ea02093a3a2fc5e8b5316ac84df0a5
    helm.sh/chart: paved-road-service-12.3.0
    helm.toolkit.fluxcd.io/name: {{.Name}}
    helm.toolkit.fluxcd.io/namespace: {{.Name}}
    k8s.expediagroup.com/instance: master
    k8s.expediagroup.com/reason: branch
    k8s.expediagroup.com/release: test-usw2
    progressivedeployment.expediagroup.com/eligible: "true"
    group: load
spec:
{{if .HeadlessService}}
  clusterIP: None
{{end}}
  selector:
    svc: {{.Name}}
  ports:
  - port: 80
    targetPort: 80
