apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
       feature: exec
  template:
    metadata:
       labels:
         feature: exec
    spec:
      containers:
      - name: agnhost
        image: 344791879147.dkr.ecr.us-west-2.amazonaws.com/thirdparty/registry.k8s.io/e2e-test-images/agnhost:2.32
